Merge test and publish workflow
noosenergy/noos-circleci-orb pull request #29
Opened 2023-08-11 17:07 UTC by zyassine

2023-08-12 10:23 UTC, pieeri requested changes
Referring to CircleCI documentation on filters:
https://circleci.com/docs/configuration-reference/#tags

In relation to the project main config file, `config.yml`, the workflow isn't triggered by default on git tags. To run the workflow, a tag filter needs to be added. As a reference,
https://github.com/CircleCI-Public/Orb-Template/blob/main/.circleci/config.yml#L9

Another good working example for master/tag workflow switch,
https://github.com/noosenergy/noos-invoke/blob/master/.circleci/config.yml#L112

2023-08-12 14:51 UTC, zyassine commented
per the documentation, I added filters for all jobs

2023-08-14 14:23 UTC, pieeri commented on .circleci/test-deploy.yml
>            filters: *filters
No filters on git tags required here ; only run workflow jobs on all branches.

2023-08-14 14:44 UTC, pieeri requested changes
Last breadcrumb left behind.

2023-08-14 14:44 UTC, pieeri commented on .circleci/test-deploy.yml
> +filters: &filters
Block to be removed ; not required. After that, good to go! Well done!

2023-08-14 14:59 UTC, pieeri approved these changes
LGTM! Thanks a lot!

2023-08-14 15:02 UTC, merged