NOOS-914/ai-pr-review
noosenergy/noos-circleci-orb pull request #44
Opened 2024-10-07 14:54 UTC by zyassine

**SEMVER Update Type:**
- [x] Major
- [ ] Minor
- [ ] Patch

## Description:

## Motivation:

 **Closes Issues:**
-  [ISSUE URL](https://noosenergy.atlassian.net/browse/NOOS-914)

## Checklist:

- [x] All new jobs, commands, executors, parameters have descriptions.
- [x] Usage Example version numbers have been updated.
- [x] Changelog has been updated.

2024-10-07 16:11 UTC, zyassine commented
/review

2024-10-08 10:43 UTC, pieeri requested changes
🏓

2024-10-08 10:43 UTC, pieeri commented on .circleci/test-deploy.yml
> +  integration_test_trigger_pr_review:
🐼 

Maybe reuse the command name in the integration test for clarity, similarly to other tests?

`integration_test_github_post_comment`

2024-10-08 10:43 UTC, pieeri commented on src/commands/github_post_comment.yml
> +  comment:
🐼 

What about adding a value by default, e.g. `/review`?

2024-10-08 10:43 UTC, pieeri commented on .github/workflows/pr_agent_template.yml
> +          OPENAI_KEY: ${{ inputs.openai_key }}
❓ 

Given such secrets are shared across the Github organisation for our repositories, is it necessary to template their value?

2024-10-08 12:26 UTC, zyassine commented
/review

2024-10-08 14:37 UTC, zyassine commented
/review

2024-10-08 14:50 UTC, zyassine commented
/review

2024-10-08 14:53 UTC, zyassine commented
/review

2024-10-08 14:53 UTC, zyassine commented
/help

2024-10-08 15:36 UTC, zyassine commented
/review

2024-10-08 15:42 UTC, zyassine commented
/review

2024-10-08 15:45 UTC, zyassine commented
/review

2024-10-08 15:47 UTC, zyassine commented
/review

2024-10-08 15:53 UTC, zyassine commented
/review

2024-10-08 15:58 UTC, zyassine commented
/review

2024-10-08 16:04 UTC, zyassine commented
/review

2024-10-08 16:07 UTC, zyassine commented
/review

2024-10-08 16:10 UTC, zyassine commented
/review

2024-10-08 16:18 UTC, zyassine commented
/review

2024-10-08 16:20 UTC, zyassine commented
/review

2024-10-08 16:29 UTC, zyassine commented
/review

2024-10-08 20:36 UTC, pieeri requested changes
Eventually the PR Agent is alive! Thanks for throwing the time in to make it work!

2024-10-08 20:36 UTC, pieeri commented on src/commands/github_post_comment.yml
> +          set -- "$@" -H "X-GitHub-Api-Version: 2022-11-28"
🐼 

Maybe as suggested by the AI PR agent, what about being able to pass the Github API version as a parameter?

2024-10-08 20:36 UTC, pieeri commented on .circleci/test-deploy.yml
> +filters_non_master_only: &filter_non_master_only
🐼 

Maybe opportunistic, but good to align CircleCI YAML conventions for `filters_non_master_only` & `release-filters`!

2024-10-09 09:21 UTC, pieeri approved these changes
Let's ship!

2024-10-09 09:21 UTC, mthiboust approved these changes
Let's use it now!

2024-10-09 09:22 UTC, merged